version: '3.1'

services:
  backend:
    build: ./backend/
    networks:
      internal:
        aliases:
          - backend
  frontend:
    build: ./frontend/
    environment:
      - BACKEND_DNS=backend
    depends_on:
      - backend
    networks:
      - internal

networks:
  internal: