version: '3.1'

services:
  backend:
    build: ./backend/
    ports:
      - 9000:9000
    networks:
      - internal
  frontend:
    build: ./frontend/
    environment:
      - BACKEND_DNS=backend_con
    depends_on:
      - backend
    networks:
      - internal

networks:
  internal: