name: Development CI

on:
  push:
    branches:
      'dev/**'

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install GO
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Build backend
        run: cd backend && go build .
      - name: Build frontend
        run: cd frontend && go build .
      - name: Upload build
        uses: actions/upload-artifact@v3
        with: 
          name: build
          path: |
            .
            !.git
            !.github
  Docker-frontend:
    runs-on: self-hosted
    needs: Build
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build
          path: .
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./frontend/Dockerfile
          push: true
          tags: user/app:latest