name: Development CI

on:
  push:
    branches:
      'dev/**'

jobs:
  Build:
    runs-on: self-hosted
    container: golang:1.18-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build backend
        run: cd backend && go build .
      - name: Build frontend
        run: cd frontend && go build .
      - name: Upload build
        uses: actions/upload-artifact@v2
        with: 
          name: build
          path: .