name: Development CI

on:
  push:
    branches:
      'dev/**'

jobs:
  Build-backend:
    runs-on: ubuntu-latest
    container: golang:1.18
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build backend
        run: cd backend && go build .
      - name: Upload build
        uses: actions/upload-artifact@v3
        with: 
          name: backend
          path: |
            .
            !.git
            !.github
  Build-frontend:
    runs-on: ubuntu-latest
    container: golang:1.18
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build frontend
        run: cd frontend && go build .
      - name: Upload build
        uses: actions/upload-artifact@v3
        with: 
          name: frontend
          path: |
            .
            !.git
            !.github