name: Go CI

on: [push, pull_request]

jobs:
  Build:
    runs-on: self-hosted
    container: golang:1.18-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build backend
        run: cd backend && go build .
      - name: Build frontend
        run: cd frontend && go build .
      - name: Upload build
        uses: actions/upload-artifact@v2
        with: 
          name: build
          path: .
  Test:
    runs-on: self-hosted
    container: golang:1.18-alpine
    needs: Build
    if: github.event_name == 'pull_request'
    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: .
      - name: Test
        run: cd frontend && go test