name: Production CD

on:
  push:
    branches:
      'production'

jobs:
  Build:
    runs-on: ubuntu-latest
    container: golang:1.18
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build backend
        run: cd backend && go build .
      - name: Build frontend
        run: cd frontend && go build .
      - name: Upload build
        uses: actions/upload-artifact@v3
        with: 
          name: backend
          path: |
            .
            !.git
            !.github
  Test-frontend:
    runs-on: ubuntu-latest
    container: golang:1.18
    needs: Build
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: frontend
          path: .
      - name: Install GCC
        run: apt update && apt install build-essential -y
      - name: Test
        run: cd frontend && go test
  Docker-push-backend:
    runs-on: self-hosted
    needs: Build
    steps:
      - name: Download code
        uses: actions/download-artifact@v3
        with:
          name: backend
          path: .
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest
  Docker-push-frontend:
    runs-on: self-hosted
    needs: Test-frontend
    steps:
      - name: Download code
        uses: actions/download-artifact@v3
        with:
          name: frontend
          path: .
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest
  Deploy:
    runs-on: self-hosted
    needs: [Docker-push-backend, Docker-push-frontend]
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: backend
          path: .
      - name: Stop running process
        run: docker-compose down
      - name: Run docker-compose
        run: docker-compose up -d