name: Staging CI

on:
  pull_request:
    branches:
      'main'

jobs:
  Build-backend:
    runs-on: ubuntu-latest
    container: golang:1.18
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build backend
        run: cd backend && go build .
      - name: Upload build
        uses: actions/upload-artifact@v3
        with: 
          name: backend
          path: |
            .
            !.git
            !.github
  Build-frontend:
    runs-on: ubuntu-latest
    container: golang:1.18
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build frontend
        run: cd frontend && go build .
      - name: Upload build
        uses: actions/upload-artifact@v3
        with: 
          name: frontend
          path: |
            .
            !.git
            !.github
  Test-frontend:
    runs-on: ubuntu-latest
    container: golang:1.18
    needs: Build-frontend
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: frontend
          path: .
      - name: Install GCC
        run: apt update && apt install build-essential -y
      - name: Test
        run: cd frontend && go test
  Docker-push-backend:
    runs-on: self-hosted
    needs: Build-backend
    steps:
      - name: Download code
        uses: actions/download-artifact@v3
        with:
          name: backend
          path: .
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest
  Docker-push-frontend:
    runs-on: self-hosted
    needs: Test-frontend
    steps:
      - name: Download code
        uses: actions/download-artifact@v3
        with:
          name: frontend
          path: .
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest